//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeMessges {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeMessges() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMA.Resources.CodeMessges", typeof(CodeMessges).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100002.
        /// </summary>
        public static string _100002Code {
            get {
                return ResourceManager.GetString("100002Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100003.
        /// </summary>
        public static string _100003Code {
            get {
                return ResourceManager.GetString("100003Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100007.
        /// </summary>
        public static string _100007Code {
            get {
                return ResourceManager.GetString("100007Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100008.
        /// </summary>
        public static string _100008Code {
            get {
                return ResourceManager.GetString("100008Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100009.
        /// </summary>
        public static string _100009Code {
            get {
                return ResourceManager.GetString("100009Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100011.
        /// </summary>
        public static string _100011Code {
            get {
                return ResourceManager.GetString("100011Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100015.
        /// </summary>
        public static string _100015Code {
            get {
                return ResourceManager.GetString("100015Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100016.
        /// </summary>
        public static string _100016Code {
            get {
                return ResourceManager.GetString("100016Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100017.
        /// </summary>
        public static string _100017Code {
            get {
                return ResourceManager.GetString("100017Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100018.
        /// </summary>
        public static string _100018Code {
            get {
                return ResourceManager.GetString("100018Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100022.
        /// </summary>
        public static string _100022Code {
            get {
                return ResourceManager.GetString("100022Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100027.
        /// </summary>
        public static string _100027Code {
            get {
                return ResourceManager.GetString("100027Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100028.
        /// </summary>
        public static string _100028Code {
            get {
                return ResourceManager.GetString("100028Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100031.
        /// </summary>
        public static string _100031Code {
            get {
                return ResourceManager.GetString("100031Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100033.
        /// </summary>
        public static string _100033Code {
            get {
                return ResourceManager.GetString("100033Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100035.
        /// </summary>
        public static string _100035Code {
            get {
                return ResourceManager.GetString("100035Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100039.
        /// </summary>
        public static string _100039Code {
            get {
                return ResourceManager.GetString("100039Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100040.
        /// </summary>
        public static string _100040Code {
            get {
                return ResourceManager.GetString("100040Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100041.
        /// </summary>
        public static string _100041Code {
            get {
                return ResourceManager.GetString("100041Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100042.
        /// </summary>
        public static string _100042Code {
            get {
                return ResourceManager.GetString("100042Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100047.
        /// </summary>
        public static string _100047Code {
            get {
                return ResourceManager.GetString("100047Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100048.
        /// </summary>
        public static string _100048Code {
            get {
                return ResourceManager.GetString("100048Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100051.
        /// </summary>
        public static string _100051Code {
            get {
                return ResourceManager.GetString("100051Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100052.
        /// </summary>
        public static string _100052Code {
            get {
                return ResourceManager.GetString("100052Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100053.
        /// </summary>
        public static string _100053Code {
            get {
                return ResourceManager.GetString("100053Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100054.
        /// </summary>
        public static string _100054Code {
            get {
                return ResourceManager.GetString("100054Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100055.
        /// </summary>
        public static string _100055Code {
            get {
                return ResourceManager.GetString("100055Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100056.
        /// </summary>
        public static string _100056Code {
            get {
                return ResourceManager.GetString("100056Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100057.
        /// </summary>
        public static string _100057Code {
            get {
                return ResourceManager.GetString("100057Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100058.
        /// </summary>
        public static string _100058Code {
            get {
                return ResourceManager.GetString("100058Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100059.
        /// </summary>
        public static string _100059Code {
            get {
                return ResourceManager.GetString("100059Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100060.
        /// </summary>
        public static string _100060Code {
            get {
                return ResourceManager.GetString("100060Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100061.
        /// </summary>
        public static string _100061Code {
            get {
                return ResourceManager.GetString("100061Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100062.
        /// </summary>
        public static string _100062Code {
            get {
                return ResourceManager.GetString("100062Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100063.
        /// </summary>
        public static string _100063Code {
            get {
                return ResourceManager.GetString("100063Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100064.
        /// </summary>
        public static string _100064Code {
            get {
                return ResourceManager.GetString("100064Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100065.
        /// </summary>
        public static string _100065Code {
            get {
                return ResourceManager.GetString("100065Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100066.
        /// </summary>
        public static string _100066Code {
            get {
                return ResourceManager.GetString("100066Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100067.
        /// </summary>
        public static string _100067Code {
            get {
                return ResourceManager.GetString("100067Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200.
        /// </summary>
        public static string _200Code {
            get {
                return ResourceManager.GetString("200Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400.
        /// </summary>
        public static string _400Code {
            get {
                return ResourceManager.GetString("400Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 401.
        /// </summary>
        public static string _401Code {
            get {
                return ResourceManager.GetString("401Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404.
        /// </summary>
        public static string _404Code {
            get {
                return ResourceManager.GetString("404Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        public static string _500Code {
            get {
                return ResourceManager.GetString("500Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (0|\+98)?([ ]|-|[()]){0,2}9[1|2|3|4]([ ]|-|[()]){0,2}(?:[0-9]([ ]|-|[()]){0,2}){8}.
        /// </summary>
        public static string MobileRegex {
            get {
                return ResourceManager.GetString("MobileRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0|\+98)[1-9]{2}[0-9]{8}$.
        /// </summary>
        public static string PhoneRegex {
            get {
                return ResourceManager.GetString("PhoneRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \b(?!(\d)\1{3})[13-9]{4}[1346-9][013-9]{5}\b.
        /// </summary>
        public static string PostalCodeRegex {
            get {
                return ResourceManager.GetString("PostalCodeRegex", resourceCulture);
            }
        }
    }
}
