//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMA.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به دسترسی به این بخش نمی باشید.
        /// </summary>
        public static string AccessDeny {
            get {
                return ResourceManager.GetString("AccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد آدرس اجباری است.
        /// </summary>
        public static string AddressTypeCodeIsNotNullable {
            get {
                return ResourceManager.GetString("AddressTypeCodeIsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اجباری است.
        /// </summary>
        public static string AddressTypeNameIsNotNullable {
            get {
                return ResourceManager.GetString("AddressTypeNameIsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان احتمال از دست دادن ارزش دارایی نمی تواند بیشتر از 100 باشد.
        /// </summary>
        public static string ALEError {
            get {
                return ResourceManager.GetString("ALEError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نام ذینفع باید بدون کاراکتر فاصله حداقل 6 کاراکتر باشد.
        /// </summary>
        public static string BeneficiaryNameContainsSpaceMoreThanLimitError {
            get {
                return ResourceManager.GetString("BeneficiaryNameContainsSpaceMoreThanLimitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ذینفع باید لاتین باشد..
        /// </summary>
        public static string BeneficiaryNameNotValidError {
            get {
                return ResourceManager.GetString("BeneficiaryNameNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد شعبه مورد نظر اشتباه است. لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string BranchCodeError {
            get {
                return ResourceManager.GetString("BranchCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه ها نباید نزدیک هم باشند!.
        /// </summary>
        public static string BranchDistanceException {
            get {
                return ResourceManager.GetString("BranchDistanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این کاربر شعبه ای تعریف نشده است!.
        /// </summary>
        public static string BranchIsNotDefinedWithUserId {
            get {
                return ResourceManager.GetString("BranchIsNotDefinedWithUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل انتخاب شده برای شعبه با یک شعبه دیگر همپوشانی دارد.
        /// </summary>
        public static string BranchLocationHasOverlapError {
            get {
                return ResourceManager.GetString("BranchLocationHasOverlapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارگزار انتخابی با کارگزار پاسخ استعلام مطابقت ندارد.
        /// </summary>
        public static string BrokerNotValid {
            get {
                return ResourceManager.GetString("BrokerNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کارگزار انتخاب شده با حواله استعلام شده مطابقت ندارد..
        /// </summary>
        public static string BrokerTypeErrorInTrustyDraftFinal {
            get {
                return ResourceManager.GetString("BrokerTypeErrorInTrustyDraftFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عبارت امنیتی اشتباه است.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئیس شعبه و معاون آن نمی تواند یک نفر باشند..
        /// </summary>
        public static string ChiefAndDeputyAreSameException {
            get {
                return ResourceManager.GetString("ChiefAndDeputyAreSameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شناسه کوبیت اشتباه است..
        /// </summary>
        public static string CobitIdentifierASCIIError {
            get {
                return ResourceManager.GetString("CobitIdentifierASCIIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده منقضی شده است لطفا مجدا تلاش نمایید.
        /// </summary>
        public static string CodeIsExpired {
            get {
                return ResourceManager.GetString("CodeIsExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده اشتباه می باشد.
        /// </summary>
        public static string CodeNotValid {
            get {
                return ResourceManager.GetString("CodeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رنگ اعالم شده صحیح نمی باشد..
        /// </summary>
        public static string ColorHexCodeIsInorrectError {
            get {
                return ResourceManager.GetString("ColorHexCodeIsInorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ بیشتر از 10 کاراکتر نمیتواند باشد!.
        /// </summary>
        public static string ColorMaxLengthError {
            get {
                return ResourceManager.GetString("ColorMaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت غیرفعال شده است..
        /// </summary>
        public static string ComapnyDeactiveError {
            get {
                return ResourceManager.GetString("ComapnyDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت حذف شده است..
        /// </summary>
        public static string ComapnyDeleteError {
            get {
                return ResourceManager.GetString("ComapnyDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مورد نظر یافت نشد..
        /// </summary>
        public static string CompanyNotFoundError {
            get {
                return ResourceManager.GetString("CompanyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  لطفا تکرار کلمه عبور جدید را وارد نمایید.
        /// </summary>
        public static string ConfirmNewPasswordIsNull {
            get {
                return ResourceManager.GetString("ConfirmNewPasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور با کلمه عبور جدید مغایرت دارد.
        /// </summary>
        public static string ConfirmPasswordNotValid {
            get {
                return ResourceManager.GetString("ConfirmPasswordNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا ثبت حواحه خود را تکمیل نمایید.
        /// </summary>
        public static string ContinueForAddDraft {
            get {
                return ResourceManager.GetString("ContinueForAddDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی ایجاد مورد برای این فرایند را ندارید.
        /// </summary>
        public static string CreateIssueWithChechActorException {
            get {
                return ResourceManager.GetString("CreateIssueWithChechActorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارز درخواست با استعلام مطابقت ندارد.
        /// </summary>
        public static string CurrencyTypeError {
            get {
                return ResourceManager.GetString("CurrencyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر قادر است حداکثر سه نوع ارز را در یک استعلام درخواست نماید.
        /// </summary>
        public static string CurrencyTypeOverCountError {
            get {
                return ResourceManager.GetString("CurrencyTypeOverCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری وجود ندارد.
        /// </summary>
        public static string CustomerIsNull {
            get {
                return ResourceManager.GetString("CustomerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مشتزی اشتباه است!.
        /// </summary>
        public static string CustomerNumberNotValidError {
            get {
                return ResourceManager.GetString("CustomerNumberNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز شروع نمیتواند بعد از روز پایان باشد..
        /// </summary>
        public static string DateOnlyError {
            get {
                return ResourceManager.GetString("DateOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ختمه وظیفه گذشته است.
        /// </summary>
        public static string DeadlineIsOverDueWarning {
            get {
                return ResourceManager.GetString("DeadlineIsOverDueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان غیرفعال شده است..
        /// </summary>
        public static string DepartmentDeactiveError {
            get {
                return ResourceManager.GetString("DepartmentDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان حذف شده است..
        /// </summary>
        public static string DepartmentDeleteError {
            get {
                return ResourceManager.GetString("DepartmentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان مورد نظر یافت نشد..
        /// </summary>
        public static string DepartmentNotFoundError {
            get {
                return ResourceManager.GetString("DepartmentNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصورت انتخاب نوع پرداخت واریز به حساب، شماره پروفرما اجباری است..
        /// </summary>
        public static string DepositProformaCurrencyTypeIdException {
            get {
                return ResourceManager.GetString("DepositProformaCurrencyTypeIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار زیر سامانه نمیتواند خالی باشد.
        /// </summary>
        public static string DomainIsNotNull {
            get {
                return ResourceManager.GetString("DomainIsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دانلود با خطا مواجه شد، فایل مورد نظر یافت نشد..
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حواله مورد نظر در جریان می باشد.
        /// </summary>
        public static string DraftInProgress {
            get {
                return ResourceManager.GetString("DraftInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره ثبت سفارش یا نام ذی نفع اشتباه است..
        /// </summary>
        public static string DraftOriginNumberAndBeneficiaryNameError {
            get {
                return ResourceManager.GetString("DraftOriginNumberAndBeneficiaryNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ درخواستی درخواست با استعلام مطابقت ندارد.
        /// </summary>
        public static string DraftRequetAmountError {
            get {
                return ResourceManager.GetString("DraftRequetAmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع حواله درخواست با استعلام مطابقت ندارد.
        /// </summary>
        public static string DraftTypeError {
            get {
                return ResourceManager.GetString("DraftTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ وارد شده باید بیشتر از تاریخ امروز باشد.
        /// </summary>
        public static string DueDateError {
            get {
                return ResourceManager.GetString("DueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان درصد از دست دادن دارایی در زمان وقوع تهدید نمیتواند بیشتر از 100 باشد.
        /// </summary>
        public static string EFError {
            get {
                return ResourceManager.GetString("EFError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در فراخوانی سرویس بهسازان.
        /// </summary>
        public static string ErrorFromBehsazanService {
            get {
                return ResourceManager.GetString("ErrorFromBehsazanService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت یا به روزرسانی در فرایند شما با خطا مواجه شده است..
        /// </summary>
        public static string ExecStoreProcedureError {
            get {
                return ResourceManager.GetString("ExecStoreProcedureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتقضاء رو به اتمام است.
        /// </summary>
        public static string ExpireDateIsCloseWarning {
            get {
                return ResourceManager.GetString("ExpireDateIsCloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقراری ارتباط با سرویس خارجی امکان پذیر نمی باشد.
        /// </summary>
        public static string ExternalServiceException {
            get {
                return ResourceManager.GetString("ExternalServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ارسال پیامک.
        /// </summary>
        public static string FailedSendSMS {
            get {
                return ResourceManager.GetString("FailedSendSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوی فایل خالی است..
        /// </summary>
        public static string FileContentNullError {
            get {
                return ResourceManager.GetString("FileContentNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر یافت نشد..
        /// </summary>
        public static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل بیش از حد مجاز است..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل نامعتبر است!.
        /// </summary>
        public static string FileTypeError {
            get {
                return ResourceManager.GetString("FileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس فایل انتخاب نشده است.
        /// </summary>
        public static string FileTypeNotSelect {
            get {
                return ResourceManager.GetString("FileTypeNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل مورد نظر پشتیبانی نمی شود..
        /// </summary>
        public static string FileTypeNotSuppurtedError {
            get {
                return ResourceManager.GetString("FileTypeNotSuppurtedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل صحیح بارگذاری نشده است..
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل با خطا مواجه شد.لطفا دوباره سعی کنید.
        /// </summary>
        public static string FileUploadException {
            get {
                return ResourceManager.GetString("FileUploadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالاها باید از نظر ویژگی و تنظیمات یکسان باشند..
        /// </summary>
        public static string GoodsConfigMustBeTheSame {
            get {
                return ResourceManager.GetString("GoodsConfigMustBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصولی یافت نشد.
        /// </summary>
        public static string GoodsIsNull {
            get {
                return ResourceManager.GetString("GoodsIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string GroupActorDuplicateError {
            get {
                return ResourceManager.GetString("GroupActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت کاربر در گروه مورد نظر غیر فعال شده است..
        /// </summary>
        public static string GroupMemberShipIsDeactiveError {
            get {
                return ResourceManager.GetString("GroupMemberShipIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت کاربر در گروه مورد نظر منقضی شده است.
        /// </summary>
        public static string GroupMemberShipIsExpiredError {
            get {
                return ResourceManager.GetString("GroupMemberShipIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string GroupPermoissionDuplicateError {
            get {
                return ResourceManager.GetString("GroupPermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا اشتباه است..
        /// </summary>
        public static string IbanIsIncorrectError {
            get {
                return ResourceManager.GetString("IbanIsIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا نامعتبر است.
        /// </summary>
        public static string IbanIsNotValid {
            get {
                return ResourceManager.GetString("IbanIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است.
        /// </summary>
        public static string InvalidUsernameOrPasswordError {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارز تعرفه انتخاب شده و نوع ارز استعلام انجام شده یکسان نیست..
        /// </summary>
        public static string InvalidWageRateException {
            get {
                return ResourceManager.GetString("InvalidWageRateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مورد یکتا نمی باشد.
        /// </summary>
        public static string IssueCodeIsNotUnique {
            get {
                return ResourceManager.GetString("IssueCodeIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل اشتباه می باشد.
        /// </summary>
        public static string IssueDueDateError {
            get {
                return ResourceManager.GetString("IssueDueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت مورد!.
        /// </summary>
        public static string IssueErrorException {
            get {
                return ResourceManager.GetString("IssueErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مورد غیرفعال شده است..
        /// </summary>
        public static string IssueTypeDeactiveError {
            get {
                return ResourceManager.GetString("IssueTypeDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مورد حذف شده است..
        /// </summary>
        public static string IssueTypeDeleteError {
            get {
                return ResourceManager.GetString("IssueTypeDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن وارد شده اشتباه می باشد!.
        /// </summary>
        public static string IssueWeightErrorException {
            get {
                return ResourceManager.GetString("IssueWeightErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نباید از 20 کاراکتر تجاوز نماید..
        /// </summary>
        public static string LengthCodeException {
            get {
                return ResourceManager.GetString("LengthCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نباید از 200 کاراکتر تجاوز نماید..
        /// </summary>
        public static string LengthNameException {
            get {
                return ResourceManager.GetString("LengthNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نباید بیش از 200 کاراکتر باشد.
        /// </summary>
        public static string LengthPaymentTypeNameException {
            get {
                return ResourceManager.GetString("LengthPaymentTypeNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه جغرافیایی مورد نظر یافت نشد..
        /// </summary>
        public static string LocationNotFoundError {
            get {
                return ResourceManager.GetString("LocationNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع منطقه جغرافیایی مورد نظر یافت نشد..
        /// </summary>
        public static string LocationTypeNotFoundError {
            get {
                return ResourceManager.GetString("LocationTypeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار حداقل وارد شده از مقدار حداکثر وارد شده بیشتر میباشد..
        /// </summary>
        public static string MinNumberBiggerThanMaxNumber {
            get {
                return ResourceManager.GetString("MinNumberBiggerThanMaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره همراه وارد شده اشتباه است..
        /// </summary>
        public static string MobileNumberRegexError {
            get {
                return ResourceManager.GetString("MobileNumberRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نا معتبر است ..
        /// </summary>
        public static string NationalCodeIsInvalidError {
            get {
                return ResourceManager.GetString("NationalCodeIsInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی مورد نظر قبلا ثبت شده است..
        /// </summary>
        public static string NationalCodeIsNotUniqueError {
            get {
                return ResourceManager.GetString("NationalCodeIsNotUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نامعتبر است.
        /// </summary>
        public static string NationalCodeIsNotValid {
            get {
                return ResourceManager.GetString("NationalCodeIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا کلمه عبور جدید را وارد نمایید.
        /// </summary>
        public static string NewPasswordIsNull {
            get {
                return ResourceManager.GetString("NewPasswordIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کارگذار ارسالی نوع کارگذاری مشخص نشده است!.
        /// </summary>
        public static string NoBrokerTypeForBrokerIdError {
            get {
                return ResourceManager.GetString("NoBrokerTypeForBrokerIdError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم انطباق داده های فرایند..
        /// </summary>
        public static string NoConditionWasCorrect {
            get {
                return ResourceManager.GetString("NoConditionWasCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن وارد شده در بازه های موجود یافت نشد..
        /// </summary>
        public static string NoMiddleIssueWeightFound {
            get {
                return ResourceManager.GetString("NoMiddleIssueWeightFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای کاربر موردنظر، شماره همراه فعالی ثبت نشده است.
        /// </summary>
        public static string NoMobileFoundError {
            get {
                return ResourceManager.GetString("NoMobileFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در این بازه زمانی شما اجازه تغییر کلمه عبور را ندارید.
        /// </summary>
        public static string NotAllowtoChangePassword {
            get {
                return ResourceManager.GetString("NotAllowtoChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات خواسته شده یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک ویو انتخاب کنید!.
        /// </summary>
        public static string NotSelectViewList {
            get {
                return ResourceManager.GetString("NotSelectViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده نمیتواند خالی باشد.
        /// </summary>
        public static string NullCodeException {
            get {
                return ResourceManager.GetString("NullCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده وارد شده نمیتواند خالی باشد.
        /// </summary>
        public static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد ارزش عددی باید تنها عدد یکتا باشد.
        /// </summary>
        public static string NumericValueNotUniqueError {
            get {
                return ResourceManager.GetString("NumericValueNotUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مرتبسازی مورد نظر پیش تر تخصیص یافته است..
        /// </summary>
        public static string OrderingAllocatedError {
            get {
                return ResourceManager.GetString("OrderingAllocatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار اولویت بندی وارد شده موجود میباشد لطفا مقدار دیگری انتخاب کنید..
        /// </summary>
        public static string OrderingNotUniqueError {
            get {
                return ResourceManager.GetString("OrderingNotUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات شبانه در حال اجرا است..
        /// </summary>
        public static string OverNightJobIsRunningError {
            get {
                return ResourceManager.GetString("OverNightJobIsRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت های راس هرم نمی توانند مجددا به عنوان یک زیر مجموعه تعریف شوند..
        /// </summary>
        public static string ParentCompaniesCannotDefinedAsChildError {
            get {
                return ResourceManager.GetString("ParentCompaniesCannotDefinedAsChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور معتبر نیست!.
        /// </summary>
        public static string PasswordNotValidException {
            get {
                return ResourceManager.GetString("PasswordNotValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی مورد نظر غیر فعال شده است.
        /// </summary>
        public static string PermissionIsDeactiveError {
            get {
                return ResourceManager.GetString("PermissionIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی مورد نظر منقضی شده است..
        /// </summary>
        public static string PermissionIsExpiredError {
            get {
                return ResourceManager.GetString("PermissionIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مورد نظر دارای یک سمت در دپارتمان انتخاب شده است..
        /// </summary>
        public static string PersonHasDuplicatePositionError {
            get {
                return ResourceManager.GetString("PersonHasDuplicatePositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت شماره تلفن وارد شده اشتباه است..
        /// </summary>
        public static string PhoneNumberRegexError {
            get {
                return ResourceManager.GetString("PhoneNumberRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت سمت مورد نظر در سازمان تکمیل شده است..
        /// </summary>
        public static string PositionAlreadyTakenError {
            get {
                return ResourceManager.GetString("PositionAlreadyTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت غیرفعال شده است..
        /// </summary>
        public static string PositionDeactiveError {
            get {
                return ResourceManager.GetString("PositionDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت حذف شده است..
        /// </summary>
        public static string PositionDeleteError {
            get {
                return ResourceManager.GetString("PositionDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت مورد نظر یافت نشد..
        /// </summary>
        public static string PositionNotFoundError {
            get {
                return ResourceManager.GetString("PositionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت کد پستی وارد شده اشتباه است..
        /// </summary>
        public static string PostalCodeRegexError {
            get {
                return ResourceManager.GetString("PostalCodeRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل مورد نظر یافت نشد..
        /// </summary>
        public static string ProfileNotFoundError {
            get {
                return ResourceManager.GetString("ProfileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جریان اجباری است !.
        /// </summary>
        public static string ProgressNameRequiredException {
            get {
                return ResourceManager.GetString("ProgressNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه مورد نظر پیش تر دارای فرآیند بوده است. فرآیند جدید در کنار فرآیند)های( قبلی بروی پروژه مورد \r\nنظر تعریف شده است.
        /// </summary>
        public static string ProjectAlreadyHasWorkflowWarning {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasWorkflowWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط یک کاربر به عنوان مدیر پروژه میتواند در نظر گرفته شود  !.
        /// </summary>
        public static string ProjectMemberIsManagerError {
            get {
                return ResourceManager.GetString("ProjectMemberIsManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه مورد نظر یافت نشد..
        /// </summary>
        public static string ProjectNotFoundError {
            get {
                return ResourceManager.GetString("ProjectNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نمیتواند خالی باشد..
        /// </summary>
        public static string QuantityNullError {
            get {
                return ResourceManager.GetString("QuantityNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده مورد نظر پیش تر تخصیص یافته است..
        /// </summary>
        public static string RangeAlreadyAllocatedError {
            get {
                return ResourceManager.GetString("RangeAlreadyAllocatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل و حداکثر محدوده انتخاب ش ده با یکدیگر مطابقت ندارند..
        /// </summary>
        public static string RangeNotValidError {
            get {
                return ResourceManager.GetString("RangeNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در برقراری ارتباط.لطفا با پشتیبانی تماس بگیرید..
        /// </summary>
        public static string RedisConnectionError {
            get {
                return ResourceManager.GetString("RedisConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این حواله نمی توانید نامه ای ثبت کنید.
        /// </summary>
        public static string RefferalLetterNotAllowCreate {
            get {
                return ResourceManager.GetString("RefferalLetterNotAllowCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه ملی نامعتبر است.
        /// </summary>
        public static string RegisterNumberIsNotValid {
            get {
                return ResourceManager.GetString("RegisterNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا {0} تکمیل نمایید .
        /// </summary>
        public static string RequiredProp {
            get {
                return ResourceManager.GetString("RequiredProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترکیب 3 فیلد درجه، احتمال ووقع و تاثیر ریسک را نباید تکراری باشد..
        /// </summary>
        public static string RiskPossibilityIdRiskImpactIdRiskDegreeIdUniqueError {
            get {
                return ResourceManager.GetString("RiskPossibilityIdRiskImpactIdRiskDegreeIdUniqueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string RoleActorDuplicateError {
            get {
                return ResourceManager.GetString("RoleActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string RolePermoissionDuplicateError {
            get {
                return ResourceManager.GetString("RolePermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته ای رخ داده است لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان دوره خدمت برای خدمات نمیتواند خالی باشد.
        /// </summary>
        public static string ServiceDuration {
            get {
                return ResourceManager.GetString("ServiceDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشست کاربری منقضی شده است..
        /// </summary>
        public static string SessionTimeoutError {
            get {
                return ResourceManager.GetString("SessionTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برخی از فعالیت ها در بروزرسانی جدید غیرفعال شده اند. لذا پرونده های موجود در این فعالیت ها نیز \r\nغیرفعال می گردند.
        /// </summary>
        public static string SomeTasksAreInteractiveInNewUpdateWarning {
            get {
                return ResourceManager.GetString("SomeTasksAreInteractiveInNewUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک فرد نمی تواند به صورت همزمان در دو شعبه متفاوت سمت داشته باشند..
        /// </summary>
        public static string StaffCantHaveRoleInTwoBranchesException {
            get {
                return ResourceManager.GetString("StaffCantHaveRoleInTwoBranchesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل خارج از دایره شهر انتخاب شده، نمی توانند به ریاست یا معاونت آن شعبه برگزیده شوند..
        /// </summary>
        public static string StaffShouldBeInSelectedException {
            get {
                return ResourceManager.GetString("StaffShouldBeInSelectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت مورد نظر یافت نشد..
        /// </summary>
        public static string StateNotFoundError {
            get {
                return ResourceManager.GetString("StateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای این گام امکان افزودن گزینه پذیرش وجود ندارد.
        /// </summary>
        public static string StepNotAllowedAddApproval {
            get {
                return ResourceManager.GetString("StepNotAllowedAddApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان اقدام به پایان رسید است..
        /// </summary>
        public static string TimeIsOverError {
            get {
                return ResourceManager.GetString("TimeIsOverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان شروع نمیتواند عقب تر زمان پایان باشد..
        /// </summary>
        public static string TimeOnlyError {
            get {
                return ResourceManager.GetString("TimeOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه هم اکنون از دسترس خارج است. لطفا بعدا تلاش فرمایید..
        /// </summary>
        public static string TimoutError {
            get {
                return ResourceManager.GetString("TimoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن منقضی شده است..
        /// </summary>
        public static string TokenIsExpiredError {
            get {
                return ResourceManager.GetString("TokenIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی به این بخش ندارید و یا نیاز به ورود مجدد دارید.
        /// </summary>
        public static string UnAuthorize {
            get {
                return ResourceManager.GetString("UnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد انتخاب شده تکراری است.
        /// </summary>
        public static string UniqueCodeError {
            get {
                return ResourceManager.GetString("UniqueCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار رتبه بندی تکراری می باشد.
        /// </summary>
        public static string UniqueOrderingError {
            get {
                return ResourceManager.GetString("UniqueOrderingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت تارنمای وارد شده اشتبا است..
        /// </summary>
        public static string UrlError {
            get {
                return ResourceManager.GetString("UrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان دوره مصرف برای کالا های مصرفی نمیتواند خالی باشد.
        /// </summary>
        public static string UsageDurationError {
            get {
                return ResourceManager.GetString("UsageDurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string UserActorDuplicateError {
            get {
                return ResourceManager.GetString("UserActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت تخصیص یافته به کاربر با فهرست شرکت های فرد مالک آن کاربر منطبق نمی باشد..
        /// </summary>
        public static string UserCompanyIsMatchWithPersonCompanyError {
            get {
                return ResourceManager.GetString("UserCompanyIsMatchWithPersonCompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از پیش دارای این گروه می باشد..
        /// </summary>
        public static string UserGroupDuplicateError {
            get {
                return ResourceManager.GetString("UserGroupDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیر فعال شده است.
        /// </summary>
        public static string UserIsDeactiveError {
            get {
                return ResourceManager.GetString("UserIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر حذف شده است ..
        /// </summary>
        public static string UserIsDeletedError {
            get {
                return ResourceManager.GetString("UserIsDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری شما به دلیل بیش از اندازه اشتباه وارد کردن  کلمه عبور قفل شده است لطفا با پشتیبانی سایت تماس حاصل فرمایید.
        /// </summary>
        public static string UserIsLocked {
            get {
                return ResourceManager.GetString("UserIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مجاز نمیباشد.
        /// </summary>
        public static string UserIsNotAuthorizedError {
            get {
                return ResourceManager.GetString("UserIsNotAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کننده باید با شعبه انتخاب شده تطابق داشته باشد..
        /// </summary>
        public static string UserIsNotInSameBranch {
            get {
                return ResourceManager.GetString("UserIsNotInSameBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در محدوده بازیگر مجاز برای اجرای این فعالیت نیست..
        /// </summary>
        public static string UserIsNotValidInActorScopeError {
            get {
                return ResourceManager.GetString("UserIsNotValidInActorScopeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است!.
        /// </summary>
        public static string UsernameNotUniqueException {
            get {
                return ResourceManager.GetString("UsernameNotUniqueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری معتبر نیست!.
        /// </summary>
        public static string UsernameNotValidException {
            get {
                return ResourceManager.GetString("UsernameNotValidException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد..
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string UserPermoissionDuplicateError {
            get {
                return ResourceManager.GetString("UserPermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از پیش دارای این نقش می باشد.
        /// </summary>
        public static string UserRoleDuplicateError {
            get {
                return ResourceManager.GetString("UserRoleDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کارمزد باید بین 0.01 تا 100 باشد!.
        /// </summary>
        public static string WagePercentageError {
            get {
                return ResourceManager.GetString("WagePercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارز با الگوی کارمزد مطابقت ندارد!.
        /// </summary>
        public static string WageRateNotMatchCurrencyType {
            get {
                return ResourceManager.GetString("WageRateNotMatchCurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام بازیگران فرآیند نمیتواند بیشتر از 200 حرف باشد.
        /// </summary>
        public static string WorkFlowActorNameError {
            get {
                return ResourceManager.GetString("WorkFlowActorNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیگر موردنظر اجازه دسترسی به همه کاربران را ندارد.
        /// </summary>
        public static string WorkFlowActorNotAccessForIsEveryOne {
            get {
                return ResourceManager.GetString("WorkFlowActorNotAccessForIsEveryOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار جدید جریان کاری با ساختار نمودار قبلی همخوانی ندارد..
        /// </summary>
        public static string WorkFlowBpmnIsChangedError {
            get {
                return ResourceManager.GetString("WorkFlowBpmnIsChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فرایند نمی تواند تکراری باشد!.
        /// </summary>
        public static string WorkFlowCodeIsUniqueException {
            get {
                return ResourceManager.GetString("WorkFlowCodeIsUniqueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرایند اجباری است!.
        /// </summary>
        public static string WorkFlowNameRequiredException {
            get {
                return ResourceManager.GetString("WorkFlowNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جریان کاری مورد نظر یافت نشد..
        /// </summary>
        public static string WorkflowNotFoundError {
            get {
                return ResourceManager.GetString("WorkflowNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع ارز انتخاب شده اشتباه است.
        /// </summary>
        public static string WrongCurrencyTypeError {
            get {
                return ResourceManager.GetString("WrongCurrencyTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشتری انتخاب شده اشتباه است.
        /// </summary>
        public static string WrongCustomerError {
            get {
                return ResourceManager.GetString("WrongCustomerError", resourceCulture);
            }
        }
    }
}
