//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIMA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIMA.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجاز به دسترسی به این بخش نمی باشید.
        /// </summary>
        public static string AccessDeny {
            get {
                return ResourceManager.GetString("AccessDeny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد آدرس اجباری است.
        /// </summary>
        public static string AddressTypeCodeIsNotNullable {
            get {
                return ResourceManager.GetString("AddressTypeCodeIsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اجباری است.
        /// </summary>
        public static string AddressTypeNameIsNotNullable {
            get {
                return ResourceManager.GetString("AddressTypeNameIsNotNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شعبه ها نباید نزدیک هم باشند!.
        /// </summary>
        public static string BranchDistanceException {
            get {
                return ResourceManager.GetString("BranchDistanceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محل انتخاب شده برای شعبه با یک شعبه دیگر همپوشانی دارد.
        /// </summary>
        public static string BranchLocationHasOverlapError {
            get {
                return ResourceManager.GetString("BranchLocationHasOverlapError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عبارت امنیتی اشتباه است.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رئیس شعبه و معاون آن نمی تواند یک نفر باشند..
        /// </summary>
        public static string ChiefAndDeputyAreSameException {
            get {
                return ResourceManager.GetString("ChiefAndDeputyAreSameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رنگ اعالم شده صحیح نمی باشد..
        /// </summary>
        public static string ColorHexCodeIsInorrectError {
            get {
                return ResourceManager.GetString("ColorHexCodeIsInorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت غیرفعال شده است..
        /// </summary>
        public static string ComapnyDeactiveError {
            get {
                return ResourceManager.GetString("ComapnyDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت حذف شده است..
        /// </summary>
        public static string ComapnyDeleteError {
            get {
                return ResourceManager.GetString("ComapnyDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت مورد نظر یافت نشد..
        /// </summary>
        public static string CompanyNotFoundError {
            get {
                return ResourceManager.GetString("CompanyNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی ایجاد مورد برای این فرایند را ندارید.
        /// </summary>
        public static string CreateIssueWithChechActorException {
            get {
                return ResourceManager.GetString("CreateIssueWithChechActorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ختمه وظیفه گذشته است.
        /// </summary>
        public static string DeadlineIsOverDueWarning {
            get {
                return ResourceManager.GetString("DeadlineIsOverDueWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان غیرفعال شده است..
        /// </summary>
        public static string DepartmentDeactiveError {
            get {
                return ResourceManager.GetString("DepartmentDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان حذف شده است..
        /// </summary>
        public static string DepartmentDeleteError {
            get {
                return ResourceManager.GetString("DepartmentDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دپارتمان مورد نظر یافت نشد..
        /// </summary>
        public static string DepartmentNotFoundError {
            get {
                return ResourceManager.GetString("DepartmentNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انتقضاء رو به اتمام است.
        /// </summary>
        public static string ExpireDateIsCloseWarning {
            get {
                return ResourceManager.GetString("ExpireDateIsCloseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برقراری ارتباط با سرویس خارجی امکان پذیر نمی باشد.
        /// </summary>
        public static string ExternalServiceException {
            get {
                return ResourceManager.GetString("ExternalServiceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل مورد نظر یافت نشد..
        /// </summary>
        public static string FileNotFoundError {
            get {
                return ResourceManager.GetString("FileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حجم فایل بیش از حد مجاز است..
        /// </summary>
        public static string FileSizeError {
            get {
                return ResourceManager.GetString("FileSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل نامعتبر است!.
        /// </summary>
        public static string FileTypeError {
            get {
                return ResourceManager.GetString("FileTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنس فایل انتخاب نشده است.
        /// </summary>
        public static string FileTypeNotSelect {
            get {
                return ResourceManager.GetString("FileTypeNotSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل مورد نظر پشتیبانی نمی شود..
        /// </summary>
        public static string FileTypeNotSuppurtedError {
            get {
                return ResourceManager.GetString("FileTypeNotSuppurtedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل صحیح بارگذاری نشده است..
        /// </summary>
        public static string FileUploadError {
            get {
                return ResourceManager.GetString("FileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل با خطا مواجه شد.لطفا دوباره سعی کنید.
        /// </summary>
        public static string FileUploadException {
            get {
                return ResourceManager.GetString("FileUploadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string GroupActorDuplicateError {
            get {
                return ResourceManager.GetString("GroupActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت کاربر در گروه مورد نظر غیر فعال شده است..
        /// </summary>
        public static string GroupMemberShipIsDeactiveError {
            get {
                return ResourceManager.GetString("GroupMemberShipIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عضویت کاربر در گروه مورد نظر منقضی شده است.
        /// </summary>
        public static string GroupMemberShipIsExpiredError {
            get {
                return ResourceManager.GetString("GroupMemberShipIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string GroupPermoissionDuplicateError {
            get {
                return ResourceManager.GetString("GroupPermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شبا اشتباه است..
        /// </summary>
        public static string IbanIsIncorrectError {
            get {
                return ResourceManager.GetString("IbanIsIncorrectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا کلمه عبور اشتباه است.
        /// </summary>
        public static string InvalidUsernameOrPasswordError {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مورد یکتا نمی باشد.
        /// </summary>
        public static string IssueCodeIsNotUnique {
            get {
                return ResourceManager.GetString("IssueCodeIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل اشتباه می باشد.
        /// </summary>
        public static string IssueDueDateError {
            get {
                return ResourceManager.GetString("IssueDueDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ثبت مورد!.
        /// </summary>
        public static string IssueErrorException {
            get {
                return ResourceManager.GetString("IssueErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مورد غیرفعال شده است..
        /// </summary>
        public static string IssueTypeDeactiveError {
            get {
                return ResourceManager.GetString("IssueTypeDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مورد حذف شده است..
        /// </summary>
        public static string IssueTypeDeleteError {
            get {
                return ResourceManager.GetString("IssueTypeDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن وارد شده اشتباه می باشد!.
        /// </summary>
        public static string IssueWeightErrorException {
            get {
                return ResourceManager.GetString("IssueWeightErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نباید از 20 کاراکتر تجاوز نماید..
        /// </summary>
        public static string LengthCodeException {
            get {
                return ResourceManager.GetString("LengthCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نباید از 200 کاراکتر تجاوز نماید..
        /// </summary>
        public static string LengthNameException {
            get {
                return ResourceManager.GetString("LengthNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان نباید بیش از 200 کاراکتر باشد.
        /// </summary>
        public static string LengthPaymentTypeNameException {
            get {
                return ResourceManager.GetString("LengthPaymentTypeNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقه جغرافیایی مورد نظر یافت نشد..
        /// </summary>
        public static string LocationNotFoundError {
            get {
                return ResourceManager.GetString("LocationNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع منطقه جغرافیایی مورد نظر یافت نشد..
        /// </summary>
        public static string LocationTypeNotFoundError {
            get {
                return ResourceManager.GetString("LocationTypeNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی نا معتبر است ..
        /// </summary>
        public static string NationalCodeIsInvalidError {
            get {
                return ResourceManager.GetString("NationalCodeIsInvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات خواسته شده یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک ویو انتخاب کنید!.
        /// </summary>
        public static string NotSelectViewList {
            get {
                return ResourceManager.GetString("NotSelectViewList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده نمیتواند خالی باشد.
        /// </summary>
        public static string NullCodeException {
            get {
                return ResourceManager.GetString("NullCodeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده وارد شده نمیتواند خالی باشد.
        /// </summary>
        public static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مرتبسازی مورد نظر پیش تر تخصیص یافته است..
        /// </summary>
        public static string OrderingAllocatedError {
            get {
                return ResourceManager.GetString("OrderingAllocatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات شبانه در حال اجرا است..
        /// </summary>
        public static string OverNightJobIsRunningError {
            get {
                return ResourceManager.GetString("OverNightJobIsRunningError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت های راس هرم نمی توانند مجددا به عنوان یک زیر مجموعه تعریف شوند..
        /// </summary>
        public static string ParentCompaniesCannotDefinedAsChildError {
            get {
                return ResourceManager.GetString("ParentCompaniesCannotDefinedAsChildError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی مورد نظر غیر فعال شده است.
        /// </summary>
        public static string PermissionIsDeactiveError {
            get {
                return ResourceManager.GetString("PermissionIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی مورد نظر منقضی شده است..
        /// </summary>
        public static string PermissionIsExpiredError {
            get {
                return ResourceManager.GetString("PermissionIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شخص مورد نظر دارای یک سمت در دپارتمان انتخاب شده است..
        /// </summary>
        public static string PersonHasDuplicatePositionError {
            get {
                return ResourceManager.GetString("PersonHasDuplicatePositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت سمت مورد نظر در سازمان تکمیل شده است..
        /// </summary>
        public static string PositionAlreadyTakenError {
            get {
                return ResourceManager.GetString("PositionAlreadyTakenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت غیرفعال شده است..
        /// </summary>
        public static string PositionDeactiveError {
            get {
                return ResourceManager.GetString("PositionDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت حذف شده است..
        /// </summary>
        public static string PositionDeleteError {
            get {
                return ResourceManager.GetString("PositionDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سمت مورد نظر یافت نشد..
        /// </summary>
        public static string PositionNotFoundError {
            get {
                return ResourceManager.GetString("PositionNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل مورد نظر یافت نشد..
        /// </summary>
        public static string ProfileNotFoundError {
            get {
                return ResourceManager.GetString("ProfileNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام جریان اجباری است !.
        /// </summary>
        public static string ProgressNameRequiredException {
            get {
                return ResourceManager.GetString("ProgressNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه مورد نظر پیش تر دارای فرآیند بوده است. فرآیند جدید در کنار فرآیند)های( قبلی بروی پروژه مورد \r\nنظر تعریف شده است.
        /// </summary>
        public static string ProjectAlreadyHasWorkflowWarning {
            get {
                return ResourceManager.GetString("ProjectAlreadyHasWorkflowWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط یک کاربر به عنوان مدیر پروژه میتواند در نظر گرفته شود  !.
        /// </summary>
        public static string ProjectMemberIsManagerError {
            get {
                return ResourceManager.GetString("ProjectMemberIsManagerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروژه مورد نظر یافت نشد..
        /// </summary>
        public static string ProjectNotFoundError {
            get {
                return ResourceManager.GetString("ProjectNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محدوده مورد نظر پیش تر تخصیص یافته است..
        /// </summary>
        public static string RangeAlreadyAllocatedError {
            get {
                return ResourceManager.GetString("RangeAlreadyAllocatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل و حداکثر محدوده انتخاب ش ده با یکدیگر مطابقت ندارند..
        /// </summary>
        public static string RangeNotValidError {
            get {
                return ResourceManager.GetString("RangeNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string RoleActorDuplicateError {
            get {
                return ResourceManager.GetString("RoleActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string RolePermoissionDuplicateError {
            get {
                return ResourceManager.GetString("RolePermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته ای رخ داده است لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشست کاربری منقضی شده است..
        /// </summary>
        public static string SessionTimeoutError {
            get {
                return ResourceManager.GetString("SessionTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برخی از فعالیت ها در بروزرسانی جدید غیرفعال شده اند. لذا پرونده های موجود در این فعالیت ها نیز \r\nغیرفعال می گردند.
        /// </summary>
        public static string SomeTasksAreInteractiveInNewUpdateWarning {
            get {
                return ResourceManager.GetString("SomeTasksAreInteractiveInNewUpdateWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک فرد نمی تواند به صورت همزمان در دو شعبه متفاوت سمت داشته باشند..
        /// </summary>
        public static string StaffCantHaveRoleInTwoBranchesException {
            get {
                return ResourceManager.GetString("StaffCantHaveRoleInTwoBranchesException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل خارج از دایره شهر انتخاب شده، نمی توانند به ریاست یا معاونت آن شعبه برگزیده شوند..
        /// </summary>
        public static string StaffShouldBeInSelectedException {
            get {
                return ResourceManager.GetString("StaffShouldBeInSelectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت مورد نظر یافت نشد..
        /// </summary>
        public static string StateNotFoundError {
            get {
                return ResourceManager.GetString("StateNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان اقدام به پایان رسید است..
        /// </summary>
        public static string TimeIsOverError {
            get {
                return ResourceManager.GetString("TimeIsOverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سامانه هم اکنون از دسترس خارج است. لطفا بعدا تلاش فرمایید..
        /// </summary>
        public static string TimoutError {
            get {
                return ResourceManager.GetString("TimoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن منقضی شده است..
        /// </summary>
        public static string TokenIsExpiredError {
            get {
                return ResourceManager.GetString("TokenIsExpiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما دسترسی به این بخش ندارید و یا نیاز به ورود مجدد دارید.
        /// </summary>
        public static string UnAuthorize {
            get {
                return ResourceManager.GetString("UnAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد انتخاب شده تکراری است.
        /// </summary>
        public static string UniqueCodeError {
            get {
                return ResourceManager.GetString("UniqueCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر پیش تر در محدوده این بازیگر فرآیند تعریف شده است..
        /// </summary>
        public static string UserActorDuplicateError {
            get {
                return ResourceManager.GetString("UserActorDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت تخصیص یافته به کاربر با فهرست شرکت های فرد مالک آن کاربر منطبق نمی باشد..
        /// </summary>
        public static string UserCompanyIsMatchWithPersonCompanyError {
            get {
                return ResourceManager.GetString("UserCompanyIsMatchWithPersonCompanyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از پیش دارای این گروه می باشد..
        /// </summary>
        public static string UserGroupDuplicateError {
            get {
                return ResourceManager.GetString("UserGroupDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر غیر فعال شده است.
        /// </summary>
        public static string UserIsDeactiveError {
            get {
                return ResourceManager.GetString("UserIsDeactiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر حذف شده است ..
        /// </summary>
        public static string UserIsDeletedError {
            get {
                return ResourceManager.GetString("UserIsDeletedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مجاز نمیباشد.
        /// </summary>
        public static string UserIsNotAuthorizedError {
            get {
                return ResourceManager.GetString("UserIsNotAuthorizedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر در محدوده بازیگر مجاز برای اجرای این فعالیت نیست..
        /// </summary>
        public static string UserIsNotValidInActorScopeError {
            get {
                return ResourceManager.GetString("UserIsNotValidInActorScopeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر یافت نشد..
        /// </summary>
        public static string UserNotFoundError {
            get {
                return ResourceManager.GetString("UserNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر مورد نظر از پیش دارای دسترسی انتخاب شده است..
        /// </summary>
        public static string UserPermoissionDuplicateError {
            get {
                return ResourceManager.GetString("UserPermoissionDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر از پیش دارای این نقش می باشد.
        /// </summary>
        public static string UserRoleDuplicateError {
            get {
                return ResourceManager.GetString("UserRoleDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمودار جدید جریان کاری با ساختار نمودار قبلی همخوانی ندارد..
        /// </summary>
        public static string WorkFlowBpmnIsChangedError {
            get {
                return ResourceManager.GetString("WorkFlowBpmnIsChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فرایند نمی تواند تکراری باشد  !.
        /// </summary>
        public static string WorkFlowCodeIsUniqueException {
            get {
                return ResourceManager.GetString("WorkFlowCodeIsUniqueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فرایند اجباری است !.
        /// </summary>
        public static string WorkFlowNameRequiredException {
            get {
                return ResourceManager.GetString("WorkFlowNameRequiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جریان کاری مورد نظر یافت نشد..
        /// </summary>
        public static string WorkflowNotFoundError {
            get {
                return ResourceManager.GetString("WorkflowNotFoundError", resourceCulture);
            }
        }
    }
}
