using SIMA.Domain.Models.Features.TrustyDrafts.BrokerInquiryStatuses.ValueObjects;

namespace SIMA.Domain.Models.Features.TrustyDrafts.TrustyDrafts.Args;

public class CreateTrustyDraftArg
{
    public long Id { get;  set; }
    public DateTime ValorDate { get;  set; }
    public string DraftNumber { get;  set; }
    public string? DraftNumberBasedOnOrder { get; set; }
    public long BranchId { get; set; }
    public long IssueId { get; set; }
    public long CustomerId { get; set; }
    public long DraftOriginId { get; set; }
    public string? CustomerAccountNumber { get; set; }
    public string? BlockNumber { get; set; }
    public DateTime? DraftIssueDate { get; set; }
    public string? BlockingNumber { get; set; }
    public decimal? DraftRequestAmount { get; set; }
    public decimal? DraftRequestAmountBasedOnUsd { get; set; }
    public decimal? DraftRequestAmountBasedOnEur { get; set; }
    public decimal? DraftNetAmount { get; set; }
    public decimal? DraftRequestNetAmountBasedOnUsd { get; set; }
    public long DraftCurrencyTypeId { get; set; }
    public long DraftNetCurrencyTypeId { get; set; }
    public string? PayingBankName { get; set; }
    public string? BrokerBankName { get; set; }
    public string? InterMediateBankName { get; set; }
    public string? BeneficiaryBankName { get; set; }
    public decimal? ExchangeWage { get; set; }
    public long ResponsibilityWageTypeId { get; set; }
    public decimal? DarftFinalWage { get; set; }
    public string? BeneficiaryName { get; set; }
    public string? RegisterCode { get; set; }
    public string? AcceptorName { get; set; }
    public DateTime? DraftAcceptDate { get; set; }
    public TimeOnly? DraftAcceptTime { get; set; }
    public string? IssueReason { get; set; }
    public string? IsFinished { get; set; }
    public DateTime? FinishDate { get; set; }
    public long FinishedBy { get; set; }
    public long AccountTypeId { get; set; }
    public long BrokerId { get; set; }
    public long StaffId { get; set; }
    public long BrokerTypeId { get; set; }
    public long DraftValorStatusId { get; set; }
    public long DraftTypeId { get; set; }
    public string? BeneficiaryAccountNumber { get; set; }
    public string? BeneficiaryAddress { get; set; }
    public string? BeneficiaryPhoneNumber { get; set; }
    public string? BeneficiaryIban { get; set; }
    public string? BeneficiaryPassportNumber { get; set; }
    public string? IntermediaryBank { get; set; }
    public string? AgentBank { get; set; }
    public string? DraftOrderNumber { get; set; }
    public long DraftStatusId { get; set; }
    public string? CustomerIban { get; set; }
    public string? CustomerPhoneNumber { get; set; }
    public string? CustomerAddress { get; set; }
    public string? CustomerNationalCode { get; set; }
    public decimal? BlockingAmount { get; set; }
    public long LoanTypeId { get; set; }
    public long DraftReviewResultId { get; set; }
    public string? RejectReason { get; set; }
    public string? CancellationReferenceNumber { get; set; }
    public DateTime? CancellationDate { get; set; }
    public decimal? CancellationAmount { get; set; }
    public long CancellationCurrencyTypeId { get; set; }
    public string? CancellationValorNumber { get; set; }
    public long CancellationResaonId { get; set; }
    public string? Description { get; set; }
    public long DraftDestinationId { get; set; }
    public string? IsFromAgentBank { get; set; }
    public long DraftCurrencyOriginId { get; set; }
    public long RequestValorId { get; set; }
    public long PaymentTypeId { get; set; }
    public long BrokerSecondLevelAddressBookId { get;  set; }
    public string? DetailBic { get;  set; }
    public decimal OriginAmount { get;  set; }
    public decimal DraftNetAmountBasedOnEur { get;  set; }
    public decimal DraftNetAmountBasedOnUsd { get;  set; }
    public string? BeneficiaryExternalAccountNumber { get;  set; }
    public string? OrderingExternalAccountNumber { get;  set; }
    public long ActiveStatusId { get; set; }
    public DateTime? CreatedAt { get; set; }
    public long CreatedBy { get; set; }
}